app:
  name: CLIENT API
  description:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: DS_APP
    password: f3H5jfd4g63lsJK
    url: jdbc:postgresql://127.0.0.1:5432/viven
    username: viven_user
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: false
    show-sql: false
logging:
  config: classpath:logback.xml
