app:
  name: VIVEN CLIENT API
  description:
  attach:
    baseDir: ${user.home}/.temp/files
    baseUrl: https://cdn.play.dev.viven.app/attach
  mail:
    enable: true
    provider: gmail
    gmail:
      username: noreply.twentyoz@gmail.com
      password: snmsyagvibtkdarb
    from: noreply.twentyoz@gmail.com
    fromName: VIVEN
  scheduled:
    enabled: false
  room:
    shareUrl: https://play.dev.viven.app/share/room
  myRoom:
    shareUrl: https://play.dev.viven.app/share/room
  avatar:
    defaultId: 9e236948-3b40-44b0-9cab-ae74031fc61c
    defaultBackgroundColor: #2A58B4
  myroom:
    defaultMapId: 96bab265-7780-4893-97f1-af72314dc2d0
    defaultPerLimit: 20
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: DS_APP
    password: f3H5jfd4g63lsJK
    url: jdbc:log4jdbc:postgresql://192.168.192.200:5432/viven
    username: viven_user
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: twentyoz.stella.misc.hibernate.SpringImplicitNamingStrategy
        physical-strategy: twentyoz.stella.misc.hibernate.SpringPhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: false
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
          databaseZone: jvm
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
mybatis:
  mapper-locations: classpath:twentyoz/viven/**/*Dao.xml
logging:
  config: classpath:logback.xml
